"""create block table

Revision ID: dcbd0e176190
Revises: ef3eab7317f7
Create Date: 2024-01-27 17:07:11.708894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcbd0e176190"
down_revision: Union[str, None] = "ef3eab7317f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocks",
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column("previous_hash", sa.String(), nullable=True),
        sa.Column("actual_hash", sa.String(), nullable=True),
        sa.Column("blockchain_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blockchain_id"],
            ["blockchain.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blocks")
    # ### end Alembic commands ###
