"""added an opportunity null columns for the blockchain table

Revision ID: 7b3d0a570246
Revises: dcbd0e176190
Create Date: 2024-01-27 22:28:15.938345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b3d0a570246"
down_revision: Union[str, None] = "dcbd0e176190"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blockchain", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("blockchain", "descr", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("blockchain", "deleted", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("blockchain", "deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("blockchain", "descr", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("blockchain", "title", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
